<?php

namespace App\Traits;

use App\Admin;
use App\Module;
use App\Privilege;

trait ModuleTrait
{
    public function storeModules()
    {
        Module::truncate();
        Privilege::truncate();
        $modules = $this->getModules();
        foreach ($modules as $module) {
            Module::create($module);
        }
    }

    public function getModules()
    {
        return [
            [ // 1
                'name' => 'Dispatcher',
                'route' => 'admin.dispatcher.index',
                'icon' => 'fa-th',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 1,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 1,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 1,
            ],
            [ // 2
                'name' => 'Booking Requests Form',
                'route' => 'admin.booking-requests-web',
                'icon' => 'fa-car',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_truncate' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 1,
                'parent' => 0,
                'sort' => 2,
            ],
            [ // 3
                'name' => 'Eagle Eye',
                'route' => 'admin.heatmap',
                'icon' => 'fa-map',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 3,
            ],
            [ // 4
                'name' => 'Push Notifications',
                'route' => 'admin.push.index',
                'icon' => 'fa-bell',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 4,
            ],
            [ // 5
                'name' => 'Reviews',
                'route' => 'admin.review',
                'icon' => 'fa-window-restore',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 5,
            ],
            [ // 6
                'name' => 'Cancellations',
                'route' => 'admin.cancellations',
                'icon' => 'fa-trash',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 6,
            ],
            [ // 7
                'name' => 'Contact Enquiries',
                'route' => 'admin.contact-enquiries',
                'icon' => 'fa-envelope-open',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 1,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 7,
            ],
            [ // 8
                'name' => 'Country View',
                'route' => 'admin.map.index',
                'icon' => 'fa-eye',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 8,
            ],
            [ // 9
                'name' => 'Users',
                'route' => 'admin.user.index',
                'icon' => 'fa-users',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 1,
                'is_status' => 1,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 1,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 9,
            ],
            [ // 10
                'name' => 'Drivers',
                'route' => 'admin.provider.index',
                'icon' => 'fa-taxi',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 1,
                'is_status' => 1,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 1,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 10,
            ],
            [ // 11
                'name' => 'Subscription(s)',
                'route' => '',
                'icon' => 'fa-money',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 15,
            ],
            [ // 12
                'name' => 'Rider Subscriptions',
                'route' => 'admin.subscription-user.index',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 11,
                'sort' => 1,
            ],
            [ // 13
                'name' => 'Driver Subscriptions',
                'route' => 'admin.subscription-provider.index',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 11,
                'sort' => 2,
            ],
            [ // 14
                'name' => 'Zones',
                'route' => '',
                'icon' => 'fa-map',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 16,
            ],
            [ // 15
                'name' => 'All Zones',
                'route' => 'admin.zone.index',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 14,
                'sort' => 1,
            ],
            [ // 16
                'name' => 'All Zone Charges',
                'route' => 'admin.zone-charges.index',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 14,
                'sort' => 2,
            ],
            [ // 17
                'name' => 'Zone Services',
                'route' => 'admin.zone-service.index',
                'icon' => 'fa-window-restore',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 11,
            ],
            [ // 18
                'name' => 'Statements',
                'route' => '',
                'icon' => 'fa-crown',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 17,
            ],
            [ // 19
                'name' => 'Overall Statments',
                'route' => 'admin.ride.statement',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 18,
                'sort' => 1,
            ],
            [ // 20
                'name' => 'Provider Statments',
                'route' => 'admin.ride.statement.provider',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 18,
                'sort' => 2,
            ],
            [ // 21
                'name' => 'Daily Statments',
                'route' => 'admin.ride.statement.today',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 18,
                'sort' => 3,
            ],
            [ // 22
                'name' => 'Monthly Statments',
                'route' => 'admin.ride.statement.monthly',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 18,
                'sort' => 4,
            ],
            [ // 23
                'name' => 'Yearly Statments',
                'route' => 'admin.ride.statement.yearly',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 18,
                'sort' => 5,
            ],
            [ // 24
                'name' => 'Documents',
                'route' => 'admin.document.index',
                'icon' => 'fa-file-alt',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_truncate' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 11,
            ],
            [ // 25
                'name' => 'Faqs',
                'route' => 'admin.faqs.index',
                'icon' => 'fa-file-alt',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 12,
            ],
            [ // 26
                'name' => 'Promocodes',
                'route' => 'admin.promocode.index',
                'icon' => 'fa-percent',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 13,
            ],
            [ // 27
                'name' => 'Services',
                'route' => 'admin.service.index',
                'icon' => 'fa-cog',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 14,
            ],
            [ // 28
                'name' => 'History',
                'route' => '',
                'icon' => 'fa-history',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 18,
            ],
            [ // 29
                'name' => 'Past History',
                'route' => 'admin.requests.index',
                'icon' => 'fa-history',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 28,
                'sort' => 1,
            ],
            [ // 30
                'name' => 'Upcoming Orders',
                'route' => 'admin.requests.scheduled',
                'icon' => 'fa-clock',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 28,
                'sort' => 2,
            ],
            [ // 31
                'name' => 'TaxiMeter History',
                'route' => 'admin.ride.meterhistory',
                'icon' => 'fa-car',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 28,
                'sort' => 3,
            ],
            [ // 32
                'name' => 'Payment History',
                'route' => 'admin.payment',
                'icon' => 'fa-wallet',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 28,
                'sort' => 4,
            ],
            [ // 33
                'name' => 'Promocode History',
                'route' => 'admin.promocode.usage',
                'icon' => 'fa-plus',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 28,
                'sort' => 5,
            ],
            [ // 34
                'name' => 'Settings',
                'route' => '',
                'icon' => 'fa-cogs',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 19,
            ],
            [ // 35
                'name' => 'Web Settings',
                'route' => 'admin.settings',
                'icon' => 'fa-cog',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 34,
                'sort' => 1,
            ],
            [ // 36
                'name' => 'App Settings',
                'route' => 'admin.settings.appsetting',
                'icon' => 'fa-mobile-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 34,
                'sort' => 2,
            ],
            [ // 37
                'name' => 'Payment Settings',
                'route' => 'admin.settings.payment',
                'icon' => 'fa-key',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 34,
                'sort' => 3,
            ],
            [ // 38
                'name' => 'Extra',
                'route' => '',
                'icon' => 'fa-th-large',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 3,
                'badged' => 0,
                'parent' => 0,
                'sort' => 20,
            ],
            [ // 39
                'name' => 'Privacy Policy',
                'route' => 'admin.privacy',
                'icon' => 'fas fa-user-secret',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 38,
                'sort' => 1,
            ],
            [ // 40
                'name' => 'Terms & Conditions',
                'route' => 'admin.terms',
                'icon' => 'fa-info-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 38,
                'sort' => 2,
            ],
            [ // 41
                'name' => 'Driver - Page',
                'route' => 'admin.driver',
                'icon' => 'fa-user',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 38,
                'sort' => 3,
            ],
            [ // 42
                'name' => 'About us',
                'route' => 'admin.about',
                'icon' => 'fa-user-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 38,
                'sort' => 4,
            ],
            [ // 43
                'name' => 'Administration',
                'route' => '',
                'icon' => 'fa-user',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 23,
            ],
            [ // 44
                'name' => 'User Roles',
                'route' => 'admin.role.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 43,
                'sort' => 1,
            ],
            [ // 45
                'name' => 'Manage Users',
                'route' => 'admin.admin.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 43,
                'sort' => 2,
            ],
            [ // 46
                'name' => 'ACCOUNTS SETTLEMENT',
                'route' => '',
                'icon' => '',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 3,
                'badged' => 0,
                'parent' => 0,
                'sort' => 22,
            ],
            [ // 47
                'name' => 'Accounts',
                'route' => '',
                'icon' => 'fa-money',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 23,
            ],
            [ // 48
                'name' => 'New Account',
                'route' => 'admin.account.index',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 47,
                'sort' => 1,
            ],
            [ // 49
                'name' => 'Approved Account',
                'route' => 'admin.account.approved',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 47,
                'sort' => 2,
            ],
            [ // 50
                'name' => 'Withdrawal',
                'route' => '',
                'icon' => 'fa-money',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 0,
                'sort' => 24,
            ],
            [ // 51
                'name' => 'Withdraw Requests',
                'route' => 'admin.withdraw.new',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 50,
                'sort' => 1,
            ],
            [ // 52
                'name' => 'Approved Requests',
                'route' => 'admin.withdraw.approved',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 50,
                'sort' => 2,
            ],
            [ // 53
                'name' => 'Disapproved Requests',
                'route' => 'admin.withdraw.disapproved',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 50,
                'sort' => 3,
            ],
            [ // 54
                'name' => 'Account Statements',
                'route' => '',
                'icon' => 'fa-money',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 3,
                'badged' => 0,
                'parent' => 0,
                'sort' => 25,
            ],
            [ // 55
                'name' => 'Overall Job Statements',
                'route' => 'admin.account.ride.statement',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 54,
                'sort' => 1,
            ],
            [ // 56
                'name' => 'Driver Statement',
                'route' => 'admin.ride.statement.provider',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 54,
                'sort' => 2,
            ],
            [ // 57
                'name' => 'Daily Statement',
                'route' => 'admin.ride.statement.today',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 54,
                'sort' => 3,
            ],
            [ // 58
                'name' => 'Monthly Statement',
                'route' => 'admin.account.ride.statement.monthly',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 54,
                'sort' => 4,
            ],
            [ // 59
                'name' => 'Yearly Statement',
                'route' => 'admin.account.ride.statement.yearly',
                'icon' => 'fa-circle',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 54,
                'sort' => 5,
            ],
            [ // 60
                'name' => 'Account',
                'route' => '',
                'icon' => 'fa-user',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 31,
            ],
            [ // 61
                'name' => 'Account Settings',
                'route' => 'admin.profile',
                'icon' => 'fa-user',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 60,
                'sort' => 1,
            ],
            [ // 62
                'name' => 'Change Password',
                'route' => 'admin.password',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 60,
                'sort' => 2,
            ],
            [ // 63
                'name' => 'Activity Logs',
                'route' => 'admin.activity-logs.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'is_truncate' => 1,
                'parent' => 43,
                'sort' => 3,
            ],
            [ // 64
                'name' => 'Dashboard',
                'route' => 'admin.dashboard',
                'icon' => 'fa-pie-chart',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 0,
            ],
            [ // 65
                'name' => 'Services',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 1,
            ],
            [ // 66
                'name' => 'Total Fleet',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 2,
            ],
            [ // 67
                'name' => 'Total Users',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 3,
            ],
            [ // 68
                'name' => 'Total Drivers',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 1,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 4,
            ],
            [ // 69
                'name' => 'Total Bookings',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 5,
            ],
            [ // 70
                'name' => 'Scheduled Bookings',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 6,
            ],
            [ // 71
                'name' => 'Driver Cancelled',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 7,
            ],
            [ // 72
                'name' => 'User Cancelled',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 8,
            ],
            [ // 73
                'name' => 'Total Revenue',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 9,
            ],
            [ // 74
                'name' => 'Total Tip',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 10,
            ],
            [ // 75
                'name' => 'Total Tip - Driver',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 11,
            ],
            [ // 76
                'name' => 'Total Tip Comission',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 12,
            ],
            [ // 77
                'name' => 'Cash Payments',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 13,
            ],
            [ // 78
                'name' => 'Online Payments',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 14,
            ],
            [ // 79
                'name' => 'iOS Users',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 15,
            ],
            [ // 80
                'name' => 'Android Users',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 16,
            ],
            [ // 81
                'name' => 'Male Users',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 17,
            ],
            [ // 82
                'name' => 'Female Users',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 18,
            ],
            [ // 83
                'name' => 'Ongoing Rides',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 19,
            ],
            [ // 84
                'name' => 'Rides Graph',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 20,
            ],
            [ // 85
                'name' => 'Payment Mode Graph',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 21,
            ],
            [ // 86
                'name' => 'User Data Graph',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 22,
            ],
            [ // 87
                'name' => 'Recent Rides Table',
                'route' => '',
                'icon' => '',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 2,
                'badged' => 0,
                'parent' => 64,
                'sort' => 23,
            ],
            [ // 88
                'name' => 'Truncate Data',
                'route' => 'admin.truncate.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 43,
                'sort' => 4,
            ],
            [ // 89
                'name' => 'Language',
                'route' => 'admin.language.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 3,
                'badged' => 0,
                'parent' => 43,
                'sort' => 5,
            ],
            [ // 90
                'name' => 'CMS',
                'route' => '',
                'icon' => 'fa-user',
                'is_view' => 0,
                'is_view_all_data' => 0,
                'is_add' => 0,
                'is_edit' => 0,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 0,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 21,
            ],
            [ // 91
                'name' => 'App CMS',
                'route' => 'admin.cms.app',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 90,
                'sort' => 3,
            ],
            [ // 92
                'name' => 'Website CMS',
                'route' => 'admin.cms.web',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 2,
                'badged' => 0,
                'parent' => 90,
                'sort' => 2,
            ],
            [ // 93
                'name' => 'Web & Admin Language',
                'route' => 'admin.language.index',
                'icon' => 'fa-exchange-alt',
                'is_view' => 1,
                'is_view_all_data' => 0,
                'is_add' => 1,
                'is_edit' => 1,
                'is_notify' => 0,
                'is_status' => 0,
                'is_delete' => 1,
                'type' => 1,
                'badged' => 0,
                'parent' => 0,
                'sort' => 22,
            ]
        ];
    }
}
